import "modern-normalize";
import "./globals.css";
import "./palette.css";
import styles from "./layout.module.css";
import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import Header from "@/components/Header/Header";
import Breadcrumbs from "@/components/Breadcrumbs/Breadcrumbs";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
  sidebar,
  modal,
}: Readonly<{
  children: React.ReactNode;
  sidebar: React.ReactNode;
  modal: React.ReactNode;
}>) {
  return (
    <html lang="en" className={`${geistSans.variable} ${geistMono.variable}`}>
      <body>
        <aside className={styles.layoutSideBar}>{sidebar}</aside>
        <div className={styles.layoutContent}>
          <header className={styles.layoutHeader}>
            <Header />
          </header>
          <nav className={styles.layoutNav}>
            <Breadcrumbs />
          </nav>
          <main className={styles.layoutMain}>{children}</main>
        </div>
        <div className={styles.layoutModalWrap}>{modal}</div>
      </body>
    </html>
  );
}
